name: Deploy para o Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy no Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-ctlfnddds78s73c6ip8g \
            -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
            -H 'Content-Type: application/json'
